image: gcc:latest

stages:
  - build
  - test

variables:
  MAKEFLAGS: "-j $(nproc)"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - "*.o"

before_script:
  - apt-get update -qq && apt-get install -y -qq libcunit1 libcunit1-dev bats
  - git submodule update --init --recursive

build:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - myprogram

test:
  stage: test
  needs: build
  script:
    - make test

